### ISSUE TITLE
Initial feedback checklist

### ISSUE THREAD

**Issue by Amoodaa** [GSG-G7/sitspot#90]
#86 checklist 
Highest priorities: 
  - Connecting Airtable to Typeforms 
    * [x] stay
    * [x] eat
    * [x] shop

### Easy fixes:
- [x] 1. Add recommendation button is not properly aligned (in mobile or desktop)
- [x] 3. the nav menu automatically closes after a link is clicked on
- [x] 5. The link for adding a new Sitspot reads a bit too casual and has a capitalization error. I would suggest 'Would you like to add a new SitSpot?"
- [x] 6. `KeyWords` in the filter search should be spelled 'Keywords'
- [x] 8. At the moment, I haven't been able to search any existing Sitspots as I don't think they are linked. 
> Search functionality done
- [x] 9. 
- [x] 10. I haven't seen the user info form - does that come next? 
  > Yes and its already implemented
Katia feedback:
- [x] 10. Landing page
   - [x] Can you please align the Shop button with the Stay button. It’s currently too long.
   - [x] Please mirror the font as per layout on https://marvelapp.com/7g2ah3f/screen/62522589 i.e. WHAT ARE YOU LOOKING FOR? And FILTER should be in capital letters. Not sure if “Search” and “Add your recommendation” are in the right font/size?
   - [x] Copy for “Welcome to our beta site”. Please write “Find” with a capital letter.
- [x] Research results page
   Font should be consistent across all pages, e.g. “WHAT ARE YOU LOOKING FOR” should be in capital letters. Currently, there’s a mix of font color (it should be all grey as per marvel app layouts) and font sizes.

### Bigger issues
- [x] 4. Copy for FAQs still need to be updated
  > (this will be assigned to @asem1789, update with data from [this word document](https://1drv.ms/u/s!AjYAThCZglCyxCLsY1bfCC5sJ7PL?e=Gs3aJm)
- [x] 7. Ideally, the keywords menu will eventually have icons beside the words
   > while this could be done, the design did not include such menu  - [keywords menu](https://user-images.githubusercontent.com/8256872/69012159-6ea29e80-097b-11ea-839f-790604823562.png)  - [keywords menu from prototype](https://marvelapp.com/7g2ah3f/screen/62522591)
- [x] Suggested Sitspots: I presume that you are working on this section and this will link to Sitspots already in the database? Note that the beach images look super distorted on the desktop.
- [x] Please confirm we are going to have a different image on each load as previously discussed.
  > I don't know about this one, we will discuss that with the team-lead because we were told that we are skipping this step. it's not hard, but let's leave it at the least priority
- [x] 13. FAQ
    Font not consistent: FAQ in the white bottom left of the header should be bigger (same size as on the “About us” header”). 
  > I think this relates to point 4 above
- [x] 14. About us
 - What is SitSpot?
  Can we add some space in between paragraphs? Currently, a bit difficult to read
 - Why do we exist
  The copy isn’t the most up to date. Please take this one 
  https://1drv.ms/w/s!AjYAThCZglCyxhm3fI_06BYvUGkW?e=wlmMwT
  - Our Values
  We are missing a space between each sentence
  - Meet the founder
  The copy isn’t the most up to date. Please take this one 
  https://1drv.ms/w/s!AjYAThCZglCyxhm3fI_06BYvUGkW?e=wlmMwT

- [x] Add place page could have the following incentive message:
  > Thank you for sharing your “sitspot”. You’re on your way to support a deserving tourism business and enlighten other conscious travelers like you. Our simple questionnaire will take 15 minutes at most to complete, and will prompt you to share the details that your fellow conscious travelers will find most helpful.

**Comment by Amoodaa** [comment]
- not possible
  >  If possible, Katia would prefer that countries/cities that do not yet have a Sitspot are not shown on the dropdown in the search. Preferably, it would look something like this, with the numbers representing the number of Sitspots in that place: 
  - why?
  > because Airtable only sends 100 records at once, and if we try to fetch 500 records at the same time, the site will stop working for 30 seconds.
 even tho, we will work on providing meaningful error handling throughout the next week, I imagine this will be the main complaint in tomorrow's user testing
